// Generated by jextract

package org.jextract.proj;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct P5_FACTORS {
 *     double meridional_scale;
 *     double parallel_scale;
 *     double areal_scale;
 *     double angular_distortion;
 *     double meridian_parallel_angle;
 *     double meridian_convergence;
 *     double tissot_semimajor;
 *     double tissot_semiminor;
 *     double dx_dlam;
 *     double dx_dphi;
 *     double dy_dlam;
 *     double dy_dphi;
 * } PJ_FACTORS
 * }
 */
public class PJ_FACTORS extends P5_FACTORS {

    PJ_FACTORS() {
        // Should not be called directly
    }
}

