// Generated by jextract

package org.jextract.proj;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct PJ_LIST {
 *     const char *id;
 *     PJ *(*proj)(PJ *);
 *     const char *const *descr;
 * } PJ_OPERATIONS
 * }
 */
public class PJ_OPERATIONS extends PJ_LIST {

    PJ_OPERATIONS() {
        // Should not be called directly
    }
}

