// Generated by jextract

package org.jextract.proj;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     double o;
 *     double p;
 *     double k;
 * }
 * }
 */
public class PJ_OPK {

    PJ_OPK() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        proj_h.C_DOUBLE.withName("o"),
        proj_h.C_DOUBLE.withName("p"),
        proj_h.C_DOUBLE.withName("k")
    ).withName("$anon$272:9");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfDouble o$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("o"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double o
     * }
     */
    public static final OfDouble o$layout() {
        return o$LAYOUT;
    }

    private static final long o$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double o
     * }
     */
    public static final long o$offset() {
        return o$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double o
     * }
     */
    public static double o(MemorySegment struct) {
        return struct.get(o$LAYOUT, o$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double o
     * }
     */
    public static void o(MemorySegment struct, double fieldValue) {
        struct.set(o$LAYOUT, o$OFFSET, fieldValue);
    }

    private static final OfDouble p$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("p"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double p
     * }
     */
    public static final OfDouble p$layout() {
        return p$LAYOUT;
    }

    private static final long p$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double p
     * }
     */
    public static final long p$offset() {
        return p$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double p
     * }
     */
    public static double p(MemorySegment struct) {
        return struct.get(p$LAYOUT, p$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double p
     * }
     */
    public static void p(MemorySegment struct, double fieldValue) {
        struct.set(p$LAYOUT, p$OFFSET, fieldValue);
    }

    private static final OfDouble k$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("k"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double k
     * }
     */
    public static final OfDouble k$layout() {
        return k$LAYOUT;
    }

    private static final long k$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double k
     * }
     */
    public static final long k$offset() {
        return k$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double k
     * }
     */
    public static double k(MemorySegment struct) {
        return struct.get(k$LAYOUT, k$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double k
     * }
     */
    public static void k(MemorySegment struct, double fieldValue) {
        struct.set(k$LAYOUT, k$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

