// Generated by jextract

package org.jextract.proj;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct PJ_UNITS {
 *     const char *id;
 *     const char *to_meter;
 *     const char *name;
 *     double factor;
 * }
 * }
 */
public class PJ_UNITS {

    PJ_UNITS() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        proj_h.C_POINTER.withName("id"),
        proj_h.C_POINTER.withName("to_meter"),
        proj_h.C_POINTER.withName("name"),
        proj_h.C_DOUBLE.withName("factor")
    ).withName("PJ_UNITS");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout id$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *id
     * }
     */
    public static final AddressLayout id$layout() {
        return id$LAYOUT;
    }

    private static final long id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *id
     * }
     */
    public static final long id$offset() {
        return id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *id
     * }
     */
    public static MemorySegment id(MemorySegment struct) {
        return struct.get(id$LAYOUT, id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *id
     * }
     */
    public static void id(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(id$LAYOUT, id$OFFSET, fieldValue);
    }

    private static final AddressLayout to_meter$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("to_meter"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *to_meter
     * }
     */
    public static final AddressLayout to_meter$layout() {
        return to_meter$LAYOUT;
    }

    private static final long to_meter$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *to_meter
     * }
     */
    public static final long to_meter$offset() {
        return to_meter$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *to_meter
     * }
     */
    public static MemorySegment to_meter(MemorySegment struct) {
        return struct.get(to_meter$LAYOUT, to_meter$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *to_meter
     * }
     */
    public static void to_meter(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(to_meter$LAYOUT, to_meter$OFFSET, fieldValue);
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final OfDouble factor$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("factor"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double factor
     * }
     */
    public static final OfDouble factor$layout() {
        return factor$LAYOUT;
    }

    private static final long factor$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double factor
     * }
     */
    public static final long factor$offset() {
        return factor$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double factor
     * }
     */
    public static double factor(MemorySegment struct) {
        return struct.get(factor$LAYOUT, factor$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double factor
     * }
     */
    public static void factor(MemorySegment struct, double fieldValue) {
        struct.set(factor$LAYOUT, factor$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

